# RCS SwiftLint Rules

disabled_rules: # rule identifiers turned on by default to exclude from running
  - comma
  - trailing_whitespace  
  - vertical_whitespace
  - opening_brace
#  - colon
#  - control_statement

#included: # paths to include during linting. `--path` is ignored if present.
#  - RemoteCarServices

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - VendoredFrameworks
  - RCSTestApp
  - RemoteCarService/*/Generated  

force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
shorthand_operator: warning

identifier_name:
  allowed_symbols: ["_"]
  min_length: 3
  excluded: 
    - on
    - in
    - at

type_name:
  allowed_symbols: ["_"]
  min_length: 3
  excluded: 
    - aCar
    - on

file_length:
  warning: 500
  error: 2500
line_length:
  warning: 200
  error: 1000
